services:
  - name: web
    type: web
    buildCommand: pip install -r requirements.txt
    startCommand: python my_app.py
    env:
      FLASK_ENV: production
      FLASK_APP: my_app.py
    healthCheckPath: /

databases: []
