services:
  - name: web
    type: web
    buildCommand: pip install -r requirements.txt
    startCommand: python my_app.py
    env:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: my_app.py
    healthCheckPath: /

databases: []
