build:
  steps:
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/my_app", "."]

  # Deploy the built Docker image to Cloud Run
deploy:
  steps:
    - name: "gcr.io/cloud-builders/gcloud"
      args:
        - "run"
        - "deploy"
        - "my_app"
        - "--image=gcr.io/$PROJECT_ID/my_app"
        - "--platform=managed"
        - "--region=us-central1"
        - "--allow-unauthenticated"
        - "--quiet"
