services:
  - name: web
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    env:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
    healthCheckPath: /

databases: []

build:
  steps:
    - name: Install Python
      id: python
      args: [ "python3" ]
    - name: Install dependencies
      id: install_dependencies
      args: ["${python.path}", "-m", "pip", "install", "-r", "requirements.txt"]
    - name: Build and start app
      id: build_and_start_app
      args: ["${python.path}", "app.py"]
